//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Autodesk, Inc")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The Dynamo Package Manager .Net Client.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.0.2.4854")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.0.2.4854")]
[assembly: System.Reflection.AssemblyProductAttribute("Greg")]
[assembly: System.Reflection.AssemblyTitleAttribute("Greg")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.0.2.4854")]

// Generated by the MSBuild WriteCodeFragment class.

