//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Autodesk, Inc")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The Dynamo Package Manager .Net Client.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.4.4853")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.4.4853+6a75fee1bdec648c63c5a14dabc4a0e588e8d831")]
[assembly: System.Reflection.AssemblyProductAttribute("Greg")]
[assembly: System.Reflection.AssemblyTitleAttribute("Greg")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.4.4853")]

// Generated by the MSBuild WriteCodeFragment class.

