version: 0.1.1
env:
  - JENKINS_NODE_WIN: "DynamoWinBuild"
  - SLACK_QUANTUM_BUILD_CHANNEL: "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID: "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT: "dynamo.dev@autodesk.com"
  - NUGET_PUBLISH_SOURCE: "https://api.nuget.org/v3/index.json"

check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification: true
language: csharp
use_garasign: true

schedule:
  cron_schedule: "once_a_week"

jenkins_creds:
    -
      type: secretText
      credentialsId: dynamovisualprogramming_nuget_api_key
      secretText: APIKEY
    -
     type: usernamePassword
     credentialsId: local-svc_p_ors
     username: GITADSK_USERNAME
     password: GITADSK_PASSWORD

build:
  -
    setup_proj_deps: true
    solution: src\\GregClient.sln
    scripts:
      - "dotnet build --configuration Release src/GregClient.sln"
ci_test:
  tests:
    -
      scripts:
        - dotnet coverage collect "dotnet test --no-build --configuration Release src/GregClient.sln --logger:junit --logger:trx" -f xml -o "coverage.xml"

  test_report_dir: src\\GregClientTests\\TestResults
  test_report_pattern:
    format: "junit"
    pattern: "*.xml"

code_analysis:
  sonarqube:
    useDotnetSonarScanner: true
    scanOnAnyBranch: true
    coverage_reports:
      - coverage.xml

soc2:
  harmony:
    hidden_email_list: dynamo_ws_access
    third_party_lib_paths:
      - bin\Release\net8.0

deployment:
  -
      type: sign
      files_to_sign:
        - "bin\\Release\\net8.0\\greg.dll"
  -
      type: customized
      scripts:
        - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\PublishPackage.ps1 -ReleaseBranches master"
