version: 0.1.1
env:
  - JENKINS_NODE_WIN: "Dynamo_Win_Perf"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.dev@autodesk.com"
  - NUGETTOOL : "Nuget\\nuget.exe"
  - NUNITTOOL : "NUnit\\NUnit.ConsoleRunner\\tools\\nunit3-console.exe"
  - URL_REPO_TOOLS : "git.autodesk.com/Dynamo/CICDResources.git"
  - BRANCH_TOOLS : "master"
  - NUGET_PUBLISH_SOURCE: "https://api.nuget.org/v3/index.json"
  - COMMON_TOOLS_DIR : "CICDResources_shared"
  - DOTCOVERTOOL : "DotCover\\JetBrains.dotCover.CommandLineTools\\tools\\dotCover.exe"
  - SONARSCANTOOL : "SonarScannerMsbuild\\dotnet-framework-sonarscanner\\tools\\SonarScanner.MSBuild.exe"
  - NUGET_SOURCES : "nuget.org"
  - NUGET_CONFIG : "Config\\nuget.config"
  - RELEASE_BRANCHES: "master,nodocker"
  
check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true
language: csharp
use_garasign: true


schedule:
  cron_schedule: "once_a_week"

jenkins_creds:
    -
      type: secretText
      credentialsId: dynamovisualprogramming_nuget_api_key
      secretText: APIKEY
    -
     type: usernamePassword
     credentialsId: local-svc_p_ors
     username: GITADSK_USERNAME 
     password: GITADSK_PASSWORD

build:
  -
    setup_proj_deps : true
    solution: src\\GregClient.sln
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\DownloadCICDResources.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_TOOLS_DIR%\\scripts\\SetupHost.ps1"
      - "dotnet build src/gregClient.sln --configuration Release"
ci_test:
  tests:
    -
      scripts:
        - dotnet test src/GregClientTests/GregClientTests.csproj --logger:"junit;LogFilePath=testresults\\testresults.xml"

  test_report_dir: src\\GregClientTests\\testresults
  test_report_pattern:
    format: "junit"
    pattern: "*.xml"

soc2:
  harmony:
    hidden_email_list: dynamo_ws_access
    third_party_lib_paths:
      - bin\\Release\\net8.0\\

deployment:
  
  -  
      type: sign
      files_to_sign:
        - "bin\\Release\\net8.0\\greg.dll"
  -
      type: customized
      scripts:
          - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\PublishPackage.ps1 -ReleaseBranches nodocker"





    
