version: 0.1.1
env:
  - JENKINS_NODE_WIN: "DynamoDockerWin"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.dev@autodesk.com"
  - DOCKER_WORKSPACE : "c:\\Greg"
  - NUGETTOOL : "Nuget\\nuget.exe"
  - DOCKER_CONTAINER : "buildContainer"
  - HARMONY_REPO : "DynamoDS/PackageManagerClient"
  
check_changelog_updated_on_pr: true
pipeline_os: "Windows"
force_slack_notification : true
language: csharp

schedule:
  cron_schedule: "once_a_month"

jenkins_creds:
    -
      type: secretText
      credentialsId: dynamovisualprogramming_nuget_api_key
      secretText: APIKEY

build:
  -
    setup_proj_deps : true
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\SetupHost.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\BuildSolution.ps1"      

soc2:
  harmony:
    hidden_email_list: dynamo_ws_access
    repository: env.HARMONY_REPO
    third_party_lib_paths:
      - "third_party"
      - "bin/release"

deployment:
    -
        type: customized
        scripts:
            - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\ExecuteContainerDeploy.ps1"
            - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\PostDeploy.ps1"
