# Build PackageManager Client using msbuild
name: PackageManagerClient-VS2022Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout PackageManagerClient Repo
        uses: actions/checkout@v4
        with:
          path: PackageManagerClient
          repository: DynamoDS/PackageManagerClient
      - name: Setup nuget
        uses: nuget/setup-nuget@v1.2
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.3
      - name: Nuget Restore PackageManagerClient solution
        run: nuget restore ${{ github.workspace }}\PackageManagerClient\src\GregClient.sln
      - name: Build PackageManagerClient with MSBuild
        run: |
          Write-Output "***Continue with the build, Good luck developer!***"
          msbuild ${{ github.workspace }}\PackageManagerClient\src\GregClient.sln
      - name: Look for PackageManagerClient
        run: |
          Write-Output "***Locating PackageManagerClient!***"
          if (Test-Path -Path "${{ github.workspace }}\PackageManagerClient\bin\Debug\net8.0\Greg.dll") {
            Write-Output "PackageManagerClient exists!"
          } else {
            Write-Error "PackageManagerClient was not found!"
          }
